-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "crm_status_sla" (
	"status" text PRIMARY KEY NOT NULL,
	"idle_days" integer DEFAULT 14 NOT NULL,
	"label" text
);
--> statement-breakpoint
ALTER TABLE "crm_status_sla" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "crm_field_defs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"label" text NOT NULL,
	"type" text NOT NULL,
	"options" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "crm_field_defs_key_uniq" UNIQUE("key"),
	CONSTRAINT "crm_field_defs_type_check" CHECK (type = ANY (ARRAY['text'::text, 'number'::text, 'boolean'::text, 'select'::text]))
);
--> statement-breakpoint
ALTER TABLE "crm_field_defs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "articles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"task_id" bigint NOT NULL,
	"url" varchar,
	"keyword_id" uuid DEFAULT gen_random_uuid()
);
--> statement-breakpoint
ALTER TABLE "articles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"title" text DEFAULT 'Nova conversa' NOT NULL,
	"messages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "calendar_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"title" text NOT NULL,
	"notes" text,
	"starts_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'planned' NOT NULL,
	"source_type" text DEFAULT 'idea' NOT NULL,
	"source_id" text,
	"post_type" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "calendar_items_post_type_check" CHECK (post_type = ANY (ARRAY['article'::text, 'social'::text])),
	CONSTRAINT "calendar_items_source_type_check" CHECK (source_type = ANY (ARRAY['idea'::text, 'task'::text, 'campaign'::text])),
	CONSTRAINT "calendar_items_status_check" CHECK (status = ANY (ARRAY['planned'::text, 'done'::text, 'canceled'::text]))
);
--> statement-breakpoint
ALTER TABLE "calendar_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "crm_companies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"domain" text,
	"org_id" text,
	"status" text DEFAULT 'lead' NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"owner_email" text,
	"industry" text,
	"size" text,
	"country" text,
	"website" text,
	"linkedin" text,
	"arr" numeric,
	"tags" text[] DEFAULT '{""}',
	"enrichment" jsonb DEFAULT '{}'::jsonb,
	"source" text DEFAULT 'manual',
	"notes" text,
	"last_activity_at" timestamp with time zone DEFAULT now(),
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"dev_count" integer,
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"tier" text,
	"deployment" text,
	"trigger" text,
	"prep_status" text DEFAULT 'not_started' NOT NULL,
	"last_outreach_at" timestamp with time zone,
	"outreach_sent_count" integer DEFAULT 0 NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "crm_companies_prep_status_check" CHECK (prep_status = ANY (ARRAY['not_started'::text, 'enriched'::text, 'ready'::text, 'parked'::text]))
);
--> statement-breakpoint
ALTER TABLE "crm_companies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "crm_comments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"author_email" text,
	"body_md" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "crm_comments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "goals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"unit" text,
	"target_count" integer DEFAULT 1 NOT NULL,
	"current_count" integer DEFAULT 0 NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"responsible_email" text,
	"project_ref" text,
	"notes" text,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"kind" text DEFAULT 'output' NOT NULL,
	"recurrence_id" uuid,
	CONSTRAINT "goals_kind_check" CHECK (kind = ANY (ARRAY['input'::text, 'output'::text])),
	CONSTRAINT "goals_priority_check" CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
	CONSTRAINT "goals_status_check" CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'missed'::text, 'paused'::text, 'archived'::text]))
);
--> statement-breakpoint
ALTER TABLE "goals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "goal_recurrences" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"unit" text,
	"target_count" integer DEFAULT 1 NOT NULL,
	"kind" text DEFAULT 'output' NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"cadence" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"responsible_email" text,
	"project_ref" text,
	"notes" text,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "goal_recurrences_cadence_check" CHECK (cadence = ANY (ARRAY['weekly'::text, 'monthly'::text])),
	CONSTRAINT "goal_recurrences_kind_check" CHECK (kind = ANY (ARRAY['input'::text, 'output'::text])),
	CONSTRAINT "goal_recurrences_priority_check" CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text]))
);
--> statement-breakpoint
ALTER TABLE "goal_recurrences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "idea_card_states" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"card_key" text NOT NULL,
	"state" text NOT NULL,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "idea_card_states_state_check" CHECK (state = ANY (ARRAY['saved'::text, 'dismissed'::text, 'promoted'::text]))
);
--> statement-breakpoint
ALTER TABLE "idea_card_states" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "job_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_id" uuid NOT NULL,
	"started_at" timestamp with time zone DEFAULT now(),
	"finished_at" timestamp with time zone,
	"status" text DEFAULT 'running',
	"result_summary" text,
	"error" text,
	"webhook_status" integer,
	CONSTRAINT "job_runs_status_check" CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text]))
);
--> statement-breakpoint
ALTER TABLE "job_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "linkedin_commenter_triggers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"commenter_id" uuid NOT NULL,
	"comment_id" text NOT NULL,
	"post_url" text NOT NULL,
	"activity_id" text,
	"post_social_id" text,
	"comment_text" text,
	"commented_at" timestamp with time zone,
	"is_reply" boolean DEFAULT false NOT NULL,
	"reaction_count" integer,
	"reply_count" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "linkedin_commenter_triggers_comment_key" UNIQUE("comment_id","commenter_id")
);
--> statement-breakpoint
ALTER TABLE "linkedin_commenter_triggers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "llm_mentions_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"snapshot_date" date NOT NULL,
	"platform" text NOT NULL,
	"mentions" integer DEFAULT 0 NOT NULL,
	"ai_search_volume" bigint DEFAULT 0 NOT NULL,
	"impressions" bigint DEFAULT 0 NOT NULL,
	"top_sources" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"top_questions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"raw_response" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "llm_mentions_snapshots_snapshot_date_platform_key" UNIQUE("platform","snapshot_date"),
	CONSTRAINT "llm_mentions_snapshots_platform_check" CHECK (platform = ANY (ARRAY['google'::text, 'chat_gpt'::text]))
);
--> statement-breakpoint
ALTER TABLE "llm_mentions_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_prospects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"domain" text NOT NULL,
	"url" text,
	"target_type" text NOT NULL,
	"contact_name" text,
	"contact_email" text,
	"contact_url" text,
	"dr" integer,
	"niche" text,
	"status" text DEFAULT 'prospect' NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"last_touch_at" timestamp with time zone,
	"next_followup_at" timestamp with time zone,
	"notes" text,
	"responsible_email" text,
	"source" text,
	"source_mention_id" uuid,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "outreach_prospects_priority_check" CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
	CONSTRAINT "outreach_prospects_status_check" CHECK (status = ANY (ARRAY['prospect'::text, 'researching'::text, 'drafted'::text, 'contacted'::text, 'replied'::text, 'won'::text, 'lost'::text, 'snoozed'::text])),
	CONSTRAINT "outreach_prospects_target_type_check" CHECK (target_type = ANY (ARRAY['listicle'::text, 'guest_post'::text, 'podcast'::text, 'awesome_list'::text, 'article'::text, 'newsletter'::text, 'partnership'::text, 'link_reclamation'::text, 'other'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_prospects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_auto_enroll_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence_id" uuid NOT NULL,
	"name" text,
	"filters" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"max_per_run" integer DEFAULT 10 NOT NULL,
	"all_contacts" boolean DEFAULT false NOT NULL,
	"last_run_at" timestamp with time zone,
	"last_result" jsonb,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "outreach_auto_enroll_rules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_enrollments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence_id" uuid NOT NULL,
	"source" text NOT NULL,
	"outreach_prospect_id" uuid,
	"research_row_id" uuid,
	"research_person_id" uuid,
	"company_name" text NOT NULL,
	"domain" text,
	"contact_name" text,
	"contact_email" text,
	"contact_linkedin" text,
	"contact_role" text,
	"status" text DEFAULT 'active' NOT NULL,
	"current_step_position" integer DEFAULT 0 NOT NULL,
	"next_run_at" timestamp with time zone,
	"last_error" text,
	"enrolled_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"crm_company_id" uuid,
	"template_vars" jsonb DEFAULT '{}'::jsonb,
	CONSTRAINT "outreach_enrollments_source_check" CHECK (source = ANY (ARRAY['research'::text, 'outreach'::text, 'manual'::text, 'crm'::text])),
	CONSTRAINT "outreach_enrollments_status_check" CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'replied'::text, 'bounced'::text, 'failed'::text, 'cancelled'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_enrollments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_reply_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_id" uuid NOT NULL,
	"gmail_message_id" text NOT NULL,
	"direction" text NOT NULL,
	"from_email" text,
	"to_emails" text[] DEFAULT '{""}' NOT NULL,
	"subject" text,
	"body_text" text,
	"body_html" text,
	"snippet" text,
	"rfc_message_id" text,
	"in_reply_to" text,
	"internal_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "outreach_reply_messages_thread_id_gmail_message_id_key" UNIQUE("gmail_message_id","thread_id"),
	CONSTRAINT "outreach_reply_messages_direction_check" CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound_ours'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_reply_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_settings" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"sending_days" smallint[] DEFAULT '{1,2,3,4,5}' NOT NULL,
	"timezone" text DEFAULT 'America/Sao_Paulo' NOT NULL,
	"updated_by_email" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "outreach_settings_id_check" CHECK (id = 'default'::text),
	CONSTRAINT "outreach_settings_sending_days_not_empty" CHECK (array_length(sending_days, 1) >= 1),
	CONSTRAINT "outreach_settings_sending_days_range" CHECK (sending_days <@ '{0,1,2,3,4,5,6}'::smallint[])
);
--> statement-breakpoint
ALTER TABLE "outreach_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_sequence_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence_id" uuid NOT NULL,
	"reason" text DEFAULT 'save' NOT NULL,
	"sequence_data" jsonb NOT NULL,
	"steps_data" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"enrollments_data" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tasks_data" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "outreach_sequence_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_people_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"row_id" uuid NOT NULL,
	"reason" text DEFAULT 'save' NOT NULL,
	"people" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"person_count" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "research_people_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid,
	"kind" text NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now(),
	"finished_at" timestamp with time zone,
	"summary" jsonb DEFAULT '{}'::jsonb,
	"last_error" text,
	"created_by" text
);
--> statement-breakpoint
ALTER TABLE "research_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_table_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"reason" text DEFAULT 'save' NOT NULL,
	"table_data" jsonb NOT NULL,
	"rows_data" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"row_count" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "research_table_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_sequences" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"default_from_email" text,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mailbox_id" uuid,
	CONSTRAINT "outreach_sequences_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'archived'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_sequences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_people" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"row_id" uuid NOT NULL,
	"name" text NOT NULL,
	"role" text,
	"linkedin" text,
	"email" text,
	"email_status" text,
	"email_source" text,
	"provider_used" text,
	"confidence" numeric,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "research_people" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "product_signals_latest" (
	"org_id" text PRIMARY KEY NOT NULL,
	"org_name" text,
	"org_type" text,
	"signup_at" timestamp with time zone,
	"connected_git" boolean DEFAULT false NOT NULL,
	"plan_type" text,
	"subscription_status" text,
	"trial_end" timestamp with time zone,
	"total_licenses" integer,
	"assigned_licenses" integer,
	"user_count" integer,
	"reviews_7d" integer,
	"reviews_30d" integer,
	"last_review_at" timestamp with time zone,
	"skips_30d" integer,
	"top_skip_reason" text,
	"tier" text,
	"trigger" text,
	"health" text,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"code_host_member_count" integer,
	"code_host_member_count_at" timestamp with time zone,
	"pr_author_count" integer,
	"dev_count" integer,
	"dev_count_source" text,
	"prs_reviewed_30d" integer,
	"suggestions_30d" integer,
	"suggestions_implemented_30d" integer,
	"suggestions_partial_30d" integer
);
--> statement-breakpoint
ALTER TABLE "product_signals_latest" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "x_reply_drafts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"candidate_id" uuid NOT NULL,
	"user_email" text NOT NULL,
	"position" integer NOT NULL,
	"angle" text NOT NULL,
	"draft_text" text NOT NULL,
	"selected" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "x_reply_drafts_angle_check" CHECK (angle = ANY (ARRAY['contrarian'::text, 'add_specificity'::text, 'sharp_question'::text]))
);
--> statement-breakpoint
ALTER TABLE "x_reply_drafts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "x_target_accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"x_username" text NOT NULL,
	"x_user_id" text NOT NULL,
	"display_name" text,
	"avatar_url" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "x_target_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "social_mentions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"platform" text NOT NULL,
	"url" text NOT NULL,
	"author" text,
	"author_profile_url" text,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"published_at" timestamp with time zone,
	"relevance" text NOT NULL,
	"intent" text NOT NULL,
	"suggested_approach" text NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"keywords_matched" text[] DEFAULT '{""}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "social_mentions_url_key" UNIQUE("url"),
	CONSTRAINT "social_mentions_intent_check" CHECK (intent = ANY (ARRAY['asking_help'::text, 'complaining'::text, 'comparing_tools'::text, 'discussing'::text, 'sharing_experience'::text, 'backlink_opportunity'::text, 'competitor_listicle'::text])),
	CONSTRAINT "social_mentions_platform_check" CHECK (platform = ANY (ARRAY['reddit'::text, 'twitter'::text, 'linkedin'::text, 'hackernews'::text, 'web'::text, 'github'::text])),
	CONSTRAINT "social_mentions_relevance_check" CHECK (relevance = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
	CONSTRAINT "social_mentions_status_check" CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'replied'::text, 'dismissed'::text]))
);
--> statement-breakpoint
ALTER TABLE "social_mentions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "brand_voice_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"scope" text DEFAULT 'kodus' NOT NULL,
	"tone" text,
	"persona" text,
	"writing_guidelines" text,
	"preferred_words" text[] DEFAULT '{""}' NOT NULL,
	"forbidden_words" text[] DEFAULT '{""}' NOT NULL,
	"additional_instructions" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"worldview" text,
	"competitor_domains" text[] DEFAULT '{""}' NOT NULL,
	CONSTRAINT "brand_voice_profiles_scope_key" UNIQUE("scope")
);
--> statement-breakpoint
ALTER TABLE "brand_voice_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "crm_activities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"summary" text,
	"meta" jsonb DEFAULT '{}'::jsonb,
	"actor_email" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "crm_activities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "crm_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"role" text,
	"phone" text,
	"linkedin" text,
	"is_primary" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "crm_contacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "growth_work_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"item_type" text DEFAULT 'idea' NOT NULL,
	"stage" text DEFAULT 'backlog' NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"source_ref" text,
	"priority" text DEFAULT 'medium' NOT NULL,
	"link" text,
	"due_at" timestamp with time zone,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"column_id" uuid,
	"position" integer DEFAULT 0,
	"responsible_email" text,
	CONSTRAINT "growth_work_items_item_type_check" CHECK (item_type = ANY (ARRAY['idea'::text, 'keyword'::text, 'title'::text, 'article'::text, 'social'::text, 'update'::text, 'task'::text])),
	CONSTRAINT "growth_work_items_priority_check" CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
	CONSTRAINT "growth_work_items_source_check" CHECK (source = ANY (ARRAY['manual'::text, 'blog'::text, 'changelog'::text, 'agent'::text, 'n8n'::text]))
);
--> statement-breakpoint
ALTER TABLE "growth_work_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "enrichment_cache" (
	"cache_key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "enrichment_cache" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "idea_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"topic" text,
	"lanes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cards" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "idea_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "linkedin_commenters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"research_table_id" uuid NOT NULL,
	"profile_url" text NOT NULL,
	"name" text NOT NULL,
	"headline" text,
	"network_distance" text,
	"provider_id" text,
	"public_identifier" text,
	"profile_picture_url" text,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "linkedin_commenters_table_profile_key" UNIQUE("profile_url","research_table_id")
);
--> statement-breakpoint
ALTER TABLE "linkedin_commenters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kanban_columns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "kanban_columns_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "kanban_columns" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "mcp_personal_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"user_email" text NOT NULL,
	"name" text NOT NULL,
	"token_prefix" text NOT NULL,
	"token_hash" text NOT NULL,
	"last_used_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mcp_personal_tokens_token_hash_key" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "mcp_personal_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_mailboxes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"label" text DEFAULT 'Outreach' NOT NULL,
	"from_name" text,
	"from_email" text NOT NULL,
	"provider" text DEFAULT 'smtp' NOT NULL,
	"smtp_host" text DEFAULT 'smtp.gmail.com' NOT NULL,
	"smtp_port" integer DEFAULT 587 NOT NULL,
	"smtp_secure" boolean DEFAULT false NOT NULL,
	"smtp_user" text,
	"smtp_pass_encrypted" text,
	"daily_cap" integer DEFAULT 40 NOT NULL,
	"is_default" boolean DEFAULT true NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"sent_today" integer DEFAULT 0 NOT NULL,
	"sent_today_date" date,
	"last_tested_at" timestamp with time zone,
	"last_test_ok" boolean,
	"last_test_error" text,
	"last_sent_at" timestamp with time zone,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"auth_method" text DEFAULT 'smtp' NOT NULL,
	"oauth_refresh_token_encrypted" text,
	"oauth_access_token_encrypted" text,
	"oauth_token_expires_at" timestamp with time zone,
	"email_auto_send" boolean DEFAULT true NOT NULL,
	"gmail_history_id" text,
	"oauth_granted_scopes" text,
	"gmail_readonly_ok" boolean,
	CONSTRAINT "outreach_mailboxes_auth_method_check" CHECK (auth_method = ANY (ARRAY['smtp'::text, 'oauth'::text])),
	CONSTRAINT "outreach_mailboxes_daily_cap_check" CHECK ((daily_cap > 0) AND (daily_cap <= 500)),
	CONSTRAINT "outreach_mailboxes_provider_check" CHECK (provider = ANY (ARRAY['smtp'::text, 'gmail'::text, 'google_oauth'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_mailboxes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_reply_threads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mailbox_id" uuid,
	"enrollment_id" uuid,
	"sequence_id" uuid,
	"gmail_thread_id" text NOT NULL,
	"contact_email" text,
	"contact_name" text,
	"company_name" text,
	"subject" text,
	"snippet" text,
	"status" text DEFAULT 'new' NOT NULL,
	"snoozed_until" timestamp with time zone,
	"matched_how" text DEFAULT 'unmatched' NOT NULL,
	"message_count" integer DEFAULT 0 NOT NULL,
	"first_inbound_at" timestamp with time zone,
	"last_inbound_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"channel" text DEFAULT 'email' NOT NULL,
	"unipile_account_id" text,
	"contact_linkedin" text,
	"reply_class" text,
	"reply_class_confidence" numeric,
	"reply_class_reason" text,
	"reply_class_model" text,
	"reply_classified_at" timestamp with time zone,
	"reply_classified_inbound_at" timestamp with time zone,
	CONSTRAINT "outreach_reply_threads_channel_check" CHECK (channel = ANY (ARRAY['email'::text, 'linkedin'::text])),
	CONSTRAINT "outreach_reply_threads_matched_how_check" CHECK (matched_how = ANY (ARRAY['gmail_thread'::text, 'in_reply_to'::text, 'from_email'::text, 'linkedin_profile'::text, 'unmatched'::text])),
	CONSTRAINT "outreach_reply_threads_reply_class_check" CHECK ((reply_class IS NULL) OR (reply_class = ANY (ARRAY['positive'::text, 'neutral'::text, 'not_now'::text, 'not_interested'::text, 'referral'::text, 'auto_reply'::text, 'unsubscribe'::text, 'bounce'::text]))),
	CONSTRAINT "outreach_reply_threads_status_check" CHECK (status = ANY (ARRAY['new'::text, 'open'::text, 'done'::text, 'snoozed'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_reply_threads" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_send_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"enrollment_id" uuid NOT NULL,
	"step_id" uuid NOT NULL,
	"channel" text NOT NULL,
	"mode" text NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"scheduled_for" timestamp with time zone DEFAULT now() NOT NULL,
	"rendered_subject" text,
	"rendered_body" text,
	"provider" text,
	"provider_message_id" text,
	"sent_at" timestamp with time zone,
	"sent_by_email" text,
	"error" text,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "outreach_send_tasks_channel_check" CHECK (channel = ANY (ARRAY['email'::text, 'linkedin'::text])),
	CONSTRAINT "outreach_send_tasks_mode_check" CHECK (mode = ANY (ARRAY['auto'::text, 'semi'::text])),
	CONSTRAINT "outreach_send_tasks_status_check" CHECK (status = ANY (ARRAY['scheduled'::text, 'ready'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'skipped'::text, 'cancelled'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_send_tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_sequence_steps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence_id" uuid NOT NULL,
	"position" integer NOT NULL,
	"channel" text NOT NULL,
	"mode" text NOT NULL,
	"delay_hours" integer DEFAULT 0 NOT NULL,
	"linkedin_action" text,
	"subject_template" text,
	"body_template" text DEFAULT '' NOT NULL,
	"stop_on_reply" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email_thread_mode" text,
	CONSTRAINT "outreach_sequence_steps_sequence_id_position_key" UNIQUE("position","sequence_id"),
	CONSTRAINT "outreach_sequence_steps_linkedin_action_check" CHECK ((linkedin_action IS NULL) OR (linkedin_action = ANY (ARRAY['connect_note'::text, 'message'::text]))),
	CONSTRAINT "outreach_sequence_steps_channel_check" CHECK (channel = ANY (ARRAY['email'::text, 'linkedin'::text])),
	CONSTRAINT "outreach_sequence_steps_delay_hours_check" CHECK (delay_hours >= 0),
	CONSTRAINT "outreach_sequence_steps_email_thread_mode_check" CHECK ((email_thread_mode IS NULL) OR (email_thread_mode = ANY (ARRAY['new'::text, 'reply'::text]))),
	CONSTRAINT "outreach_sequence_steps_mode_check" CHECK (mode = ANY (ARRAY['auto'::text, 'semi'::text]))
);
--> statement-breakpoint
ALTER TABLE "outreach_sequence_steps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "social_yolo_posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"batch_date" date NOT NULL,
	"position" integer NOT NULL,
	"lane" text NOT NULL,
	"theme" text NOT NULL,
	"platform" text NOT NULL,
	"hook" text DEFAULT '' NOT NULL,
	"content" text NOT NULL,
	"cta" text DEFAULT '' NOT NULL,
	"hashtags" text[] DEFAULT '{""}' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "social_yolo_posts_lane_check" CHECK (lane = ANY (ARRAY['blog'::text, 'changelog'::text, 'mixed'::text, 'hackernews'::text, 'research'::text, 'adversarial'::text])),
	CONSTRAINT "social_yolo_posts_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'selected'::text, 'discarded'::text]))
);
--> statement-breakpoint
ALTER TABLE "social_yolo_posts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_rows" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"company_name" text NOT NULL,
	"domain" text,
	"source" text DEFAULT 'manual' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"icp_score" numeric,
	"trigger_score" numeric,
	"fit_score" numeric,
	"anti_flags" text[] DEFAULT '{""}',
	"why_now" text,
	"pass" boolean,
	"pack_raw" jsonb DEFAULT '{}'::jsonb,
	"last_researched_at" timestamp with time zone,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"cells" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "research_rows" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "keywords" (
	"id" uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"keyword" text NOT NULL,
	"search_volume" numeric,
	"cpc" numeric,
	"competition" text,
	"idea" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"task_id" bigint,
	"language" varchar,
	"location_code" bigint
);
--> statement-breakpoint
ALTER TABLE "keywords" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_voice_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"tone" text,
	"persona" text,
	"writing_guidelines" text,
	"preferred_words" text[] DEFAULT '{""}' NOT NULL,
	"forbidden_words" text[] DEFAULT '{""}' NOT NULL,
	"additional_instructions" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"worldview" text,
	CONSTRAINT "user_voice_profiles_user_email_key" UNIQUE("user_email")
);
--> statement-breakpoint
ALTER TABLE "user_voice_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_tables" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"rubric_id" text DEFAULT 'qe-kodus-v1' NOT NULL,
	"description" text,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"rubric_json" jsonb,
	"slug" text,
	"columns" jsonb DEFAULT '[]'::jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "research_tables" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "scheduled_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"name" text NOT NULL,
	"prompt" text NOT NULL,
	"cron_expression" text NOT NULL,
	"webhook_url" text NOT NULL,
	"enabled" boolean DEFAULT true,
	"last_run_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "scheduled_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "product_signals_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" text NOT NULL,
	"tier" text,
	"trigger" text,
	"health" text,
	"plan_type" text,
	"subscription_status" text,
	"prev_tier" text,
	"prev_trigger" text,
	"reviews_30d" integer,
	"skips_30d" integer,
	"top_skip_reason" text,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "product_signals_history" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "x_reply_candidates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"target_account_id" uuid NOT NULL,
	"x_post_id" text NOT NULL,
	"post_url" text NOT NULL,
	"post_text" text NOT NULL,
	"post_created_at" timestamp with time zone NOT NULL,
	"author_username" text NOT NULL,
	"author_display_name" text,
	"author_avatar_url" text,
	"metrics" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"engagement_score" numeric DEFAULT '0' NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"snoozed_until" timestamp with time zone,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_hint" text,
	CONSTRAINT "x_reply_candidates_status_check" CHECK (status = ANY (ARRAY['new'::text, 'drafted'::text, 'dismissed'::text, 'replied'::text, 'snoozed'::text]))
);
--> statement-breakpoint
ALTER TABLE "x_reply_candidates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "task" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text
);
--> statement-breakpoint
ALTER TABLE "task" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_evidence" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"row_id" uuid NOT NULL,
	"criterion_id" text NOT NULL,
	"kind" text NOT NULL,
	"status" text NOT NULL,
	"confidence" numeric DEFAULT '0',
	"evidence" text,
	"sources" jsonb DEFAULT '[]'::jsonb,
	"weight" numeric DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "research_evidence" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_email" text NOT NULL,
	"kind" text NOT NULL,
	"severity" text DEFAULT 'info' NOT NULL,
	"title" text NOT NULL,
	"body" text,
	"source" text,
	"source_id" text,
	"link" text,
	"dedupe_key" text NOT NULL,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "user_notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "research_excluded_companies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"domain" text,
	"company_key" text NOT NULL,
	"company_name" text NOT NULL,
	"reason" text,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "research_excluded_companies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "company_enrichment" (
	"domain" text PRIMARY KEY NOT NULL,
	"employee_count" integer,
	"industry" text,
	"company_type" text,
	"country" text,
	"founded_year" integer,
	"name" text,
	"provider" text DEFAULT 'ninjapear' NOT NULL,
	"error" text,
	"raw" jsonb,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "company_enrichment" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "goal_links" (
	"goal_id" uuid NOT NULL,
	"work_item_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by_email" text,
	CONSTRAINT "goal_links_pkey" PRIMARY KEY("goal_id","work_item_id")
);
--> statement-breakpoint
ALTER TABLE "goal_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "articles" ADD CONSTRAINT "articles_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."task"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "articles" ADD CONSTRAINT "articles_keyword_id_fkey" FOREIGN KEY ("keyword_id") REFERENCES "public"."keywords"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "crm_comments" ADD CONSTRAINT "crm_comments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."crm_companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_recurrence_id_fkey" FOREIGN KEY ("recurrence_id") REFERENCES "public"."goal_recurrences"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_runs" ADD CONSTRAINT "job_runs_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."scheduled_jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "linkedin_commenter_triggers" ADD CONSTRAINT "linkedin_commenter_triggers_commenter_id_fkey" FOREIGN KEY ("commenter_id") REFERENCES "public"."linkedin_commenters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_prospects" ADD CONSTRAINT "outreach_prospects_source_mention_id_fkey" FOREIGN KEY ("source_mention_id") REFERENCES "public"."social_mentions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_auto_enroll_rules" ADD CONSTRAINT "outreach_auto_enroll_rules_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES "public"."outreach_sequences"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_enrollments" ADD CONSTRAINT "outreach_enrollments_crm_company_id_fkey" FOREIGN KEY ("crm_company_id") REFERENCES "public"."crm_companies"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_enrollments" ADD CONSTRAINT "outreach_enrollments_outreach_prospect_id_fkey" FOREIGN KEY ("outreach_prospect_id") REFERENCES "public"."outreach_prospects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_enrollments" ADD CONSTRAINT "outreach_enrollments_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES "public"."outreach_sequences"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_reply_messages" ADD CONSTRAINT "outreach_reply_messages_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "public"."outreach_reply_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_people_snapshots" ADD CONSTRAINT "research_people_snapshots_row_id_fkey" FOREIGN KEY ("row_id") REFERENCES "public"."research_rows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_runs" ADD CONSTRAINT "research_runs_table_id_fkey" FOREIGN KEY ("table_id") REFERENCES "public"."research_tables"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_sequences" ADD CONSTRAINT "outreach_sequences_mailbox_id_fkey" FOREIGN KEY ("mailbox_id") REFERENCES "public"."outreach_mailboxes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_people" ADD CONSTRAINT "research_people_row_id_fkey" FOREIGN KEY ("row_id") REFERENCES "public"."research_rows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "x_reply_drafts" ADD CONSTRAINT "x_reply_drafts_candidate_id_fkey" FOREIGN KEY ("candidate_id") REFERENCES "public"."x_reply_candidates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "crm_activities" ADD CONSTRAINT "crm_activities_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."crm_companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "crm_contacts" ADD CONSTRAINT "crm_contacts_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."crm_companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "growth_work_items" ADD CONSTRAINT "growth_work_items_column_id_fkey" FOREIGN KEY ("column_id") REFERENCES "public"."kanban_columns"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "linkedin_commenters" ADD CONSTRAINT "linkedin_commenters_research_table_id_fkey" FOREIGN KEY ("research_table_id") REFERENCES "public"."research_tables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_reply_threads" ADD CONSTRAINT "outreach_reply_threads_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "public"."outreach_enrollments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_reply_threads" ADD CONSTRAINT "outreach_reply_threads_mailbox_id_fkey" FOREIGN KEY ("mailbox_id") REFERENCES "public"."outreach_mailboxes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_reply_threads" ADD CONSTRAINT "outreach_reply_threads_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES "public"."outreach_sequences"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_send_tasks" ADD CONSTRAINT "outreach_send_tasks_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "public"."outreach_enrollments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_send_tasks" ADD CONSTRAINT "outreach_send_tasks_step_id_fkey" FOREIGN KEY ("step_id") REFERENCES "public"."outreach_sequence_steps"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_sequence_steps" ADD CONSTRAINT "outreach_sequence_steps_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES "public"."outreach_sequences"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_rows" ADD CONSTRAINT "research_rows_table_id_fkey" FOREIGN KEY ("table_id") REFERENCES "public"."research_tables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "keywords" ADD CONSTRAINT "keywords_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "x_reply_candidates" ADD CONSTRAINT "x_reply_candidates_target_account_id_fkey" FOREIGN KEY ("target_account_id") REFERENCES "public"."x_target_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_evidence" ADD CONSTRAINT "research_evidence_row_id_fkey" FOREIGN KEY ("row_id") REFERENCES "public"."research_rows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_links" ADD CONSTRAINT "goal_links_goal_id_fkey" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_links" ADD CONSTRAINT "goal_links_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "public"."growth_work_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "crm_field_defs_position_idx" ON "crm_field_defs" USING btree ("position" int4_ops,"label" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_conversations_updated_at" ON "conversations" USING btree ("updated_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_conversations_user_email" ON "conversations" USING btree ("user_email" text_ops);--> statement-breakpoint
CREATE INDEX "calendar_items_starts_at_idx" ON "calendar_items" USING btree ("starts_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "calendar_items_user_email_idx" ON "calendar_items" USING btree ("user_email" text_ops);--> statement-breakpoint
CREATE INDEX "crm_companies_active_idx" ON "crm_companies" USING btree ("last_activity_at" timestamptz_ops) WHERE (archived_at IS NULL);--> statement-breakpoint
CREATE INDEX "crm_companies_deployment_idx" ON "crm_companies" USING btree ("deployment" text_ops) WHERE (deployment IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "crm_companies_domain_uniq" ON "crm_companies" USING btree (lower(domain) text_ops) WHERE (domain IS NOT NULL);--> statement-breakpoint
CREATE INDEX "crm_companies_last_activity_idx" ON "crm_companies" USING btree ("last_activity_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "crm_companies_last_outreach_at_idx" ON "crm_companies" USING btree ("last_outreach_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "crm_companies_org_id_uniq" ON "crm_companies" USING btree ("org_id" text_ops) WHERE (org_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "crm_companies_prep_status_idx" ON "crm_companies" USING btree ("prep_status" text_ops) WHERE (prep_status = ANY (ARRAY['not_started'::text, 'enriched'::text, 'ready'::text]));--> statement-breakpoint
CREATE INDEX "crm_companies_status_idx" ON "crm_companies" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "crm_companies_tier_idx" ON "crm_companies" USING btree ("tier" text_ops) WHERE (tier IS NOT NULL);--> statement-breakpoint
CREATE INDEX "crm_companies_trigger_idx" ON "crm_companies" USING btree ("trigger" text_ops) WHERE (trigger IS NOT NULL);--> statement-breakpoint
CREATE INDEX "crm_comments_company_idx" ON "crm_comments" USING btree ("company_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "goals_period_idx" ON "goals" USING btree ("period_start" date_ops,"period_end" date_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "goals_recurrence_period_uidx" ON "goals" USING btree ("recurrence_id" date_ops,"period_start" uuid_ops) WHERE (recurrence_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "goals_responsible_idx" ON "goals" USING btree ("responsible_email" text_ops,"status" text_ops);--> statement-breakpoint
CREATE INDEX "goals_status_idx" ON "goals" USING btree ("status" date_ops,"period_end" date_ops);--> statement-breakpoint
CREATE INDEX "goal_recurrences_active_idx" ON "goal_recurrences" USING btree ("active" text_ops,"cadence" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "idea_card_states_user_card_uidx" ON "idea_card_states" USING btree ("user_email" text_ops,"card_key" text_ops);--> statement-breakpoint
CREATE INDEX "idea_card_states_user_state_idx" ON "idea_card_states" USING btree ("user_email" text_ops,"state" text_ops);--> statement-breakpoint
CREATE INDEX "idx_job_runs_job_id" ON "job_runs" USING btree ("job_id" timestamptz_ops,"started_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "linkedin_commenter_triggers_commenter_idx" ON "linkedin_commenter_triggers" USING btree ("commenter_id" timestamptz_ops,"commented_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "linkedin_commenter_triggers_post_idx" ON "linkedin_commenter_triggers" USING btree ("post_url" text_ops);--> statement-breakpoint
CREATE INDEX "idx_llm_mentions_snapshots_latest" ON "llm_mentions_snapshots" USING btree ("snapshot_date" date_ops,"platform" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_prospects_domain_idx" ON "outreach_prospects" USING btree ("domain" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_prospects_followup_idx" ON "outreach_prospects" USING btree ("next_followup_at" timestamptz_ops) WHERE (next_followup_at IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_prospects_responsible_idx" ON "outreach_prospects" USING btree ("responsible_email" text_ops,"status" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_prospects_status_idx" ON "outreach_prospects" USING btree ("status" text_ops,"created_at" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_prospects_url_unique" ON "outreach_prospects" USING btree ("url" text_ops) WHERE (url IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_auto_enroll_rules_active_idx" ON "outreach_auto_enroll_rules" USING btree ("active" bool_ops) WHERE (active = true);--> statement-breakpoint
CREATE INDEX "outreach_auto_enroll_rules_sequence_idx" ON "outreach_auto_enroll_rules" USING btree ("sequence_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "outreach_enrollments_crm_company_idx" ON "outreach_enrollments" USING btree ("crm_company_id" uuid_ops) WHERE (crm_company_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_enrollments_next_run_idx" ON "outreach_enrollments" USING btree ("next_run_at" timestamptz_ops) WHERE ((status = 'active'::text) AND (next_run_at IS NOT NULL));--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_enrollments_seq_email_uniq" ON "outreach_enrollments" USING btree (sequence_id text_ops,lower(contact_email) text_ops) WHERE ((contact_email IS NOT NULL) AND (status = ANY (ARRAY['active'::text, 'paused'::text])));--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_enrollments_seq_linkedin_uniq" ON "outreach_enrollments" USING btree ("sequence_id" text_ops,"contact_linkedin" text_ops) WHERE ((contact_linkedin IS NOT NULL) AND (status = ANY (ARRAY['active'::text, 'paused'::text])));--> statement-breakpoint
CREATE INDEX "outreach_enrollments_sequence_idx" ON "outreach_enrollments" USING btree ("sequence_id" text_ops,"status" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_reply_messages_rfc_idx" ON "outreach_reply_messages" USING btree ("rfc_message_id" text_ops) WHERE (rfc_message_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_reply_messages_thread_idx" ON "outreach_reply_messages" USING btree ("thread_id" timestamptz_ops,"internal_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "outreach_sequence_snapshots_sequence_idx" ON "outreach_sequence_snapshots" USING btree ("sequence_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "research_people_snapshots_row_idx" ON "research_people_snapshots" USING btree ("row_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "research_runs_table_idx" ON "research_runs" USING btree ("table_id" timestamptz_ops,"started_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "research_table_snapshots_table_idx" ON "research_table_snapshots" USING btree ("table_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "outreach_sequences_mailbox_idx" ON "outreach_sequences" USING btree ("mailbox_id" uuid_ops) WHERE (mailbox_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "research_people_row_idx" ON "research_people" USING btree ("row_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "product_signals_latest_dev_count_idx" ON "product_signals_latest" USING btree ("dev_count" int4_ops) WHERE (dev_count IS NOT NULL);--> statement-breakpoint
CREATE INDEX "product_signals_latest_tier_idx" ON "product_signals_latest" USING btree ("tier" text_ops) WHERE (tier IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "x_reply_drafts_candidate_position_uidx" ON "x_reply_drafts" USING btree ("candidate_id" int4_ops,"position" int4_ops);--> statement-breakpoint
CREATE INDEX "x_reply_drafts_user_idx" ON "x_reply_drafts" USING btree ("user_email" text_ops);--> statement-breakpoint
CREATE INDEX "x_target_accounts_user_enabled_idx" ON "x_target_accounts" USING btree ("user_email" text_ops,"enabled" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "x_target_accounts_user_username_uidx" ON "x_target_accounts" USING btree (user_email text_ops,lower(x_username) text_ops);--> statement-breakpoint
CREATE INDEX "idx_social_mentions_platform" ON "social_mentions" USING btree ("platform" text_ops,"created_at" text_ops);--> statement-breakpoint
CREATE INDEX "idx_social_mentions_status" ON "social_mentions" USING btree ("status" text_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "brand_voice_profiles_scope_uidx" ON "brand_voice_profiles" USING btree ("scope" text_ops);--> statement-breakpoint
CREATE INDEX "crm_activities_company_idx" ON "crm_activities" USING btree ("company_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "crm_activities_promote_note_uq" ON "crm_activities" USING btree (company_id text_ops,((meta ->> 'enrollment_id'::text)) text_ops,((meta ->> 'reason'::text)) text_ops) WHERE ((kind = 'note'::text) AND ((meta ->> 'enrollment_id'::text) IS NOT NULL));--> statement-breakpoint
CREATE INDEX "crm_contacts_active_idx" ON "crm_contacts" USING btree ("company_id" uuid_ops) WHERE (archived_at IS NULL);--> statement-breakpoint
CREATE INDEX "crm_contacts_company_idx" ON "crm_contacts" USING btree ("company_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "growth_work_items_responsible_email_idx" ON "growth_work_items" USING btree ("responsible_email" text_ops);--> statement-breakpoint
CREATE INDEX "growth_work_items_stage_idx" ON "growth_work_items" USING btree ("stage" text_ops);--> statement-breakpoint
CREATE INDEX "growth_work_items_updated_at_idx" ON "growth_work_items" USING btree ("updated_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "growth_work_items_user_email_idx" ON "growth_work_items" USING btree ("user_email" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "growth_work_items_user_source_ref_unique_idx" ON "growth_work_items" USING btree ("user_email" text_ops,"source_ref" text_ops) WHERE (source_ref IS NOT NULL);--> statement-breakpoint
CREATE INDEX "enrichment_cache_expires_idx" ON "enrichment_cache" USING btree ("expires_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idea_sessions_user_generated_idx" ON "idea_sessions" USING btree ("user_email" text_ops,"generated_at" text_ops);--> statement-breakpoint
CREATE INDEX "linkedin_commenters_distance_idx" ON "linkedin_commenters" USING btree ("research_table_id" text_ops,"network_distance" uuid_ops) WHERE (network_distance IS NOT NULL);--> statement-breakpoint
CREATE INDEX "linkedin_commenters_table_idx" ON "linkedin_commenters" USING btree ("research_table_id" timestamptz_ops,"last_seen_at" uuid_ops);--> statement-breakpoint
CREATE INDEX "mcp_personal_tokens_hash_idx" ON "mcp_personal_tokens" USING btree ("token_hash" text_ops) WHERE (revoked_at IS NULL);--> statement-breakpoint
CREATE INDEX "mcp_personal_tokens_user_id_idx" ON "mcp_personal_tokens" USING btree ("user_id" uuid_ops) WHERE (revoked_at IS NULL);--> statement-breakpoint
CREATE INDEX "outreach_mailboxes_enabled_idx" ON "outreach_mailboxes" USING btree ("enabled" bool_ops,"is_default" bool_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_mailboxes_one_default" ON "outreach_mailboxes" USING btree ("is_default" bool_ops) WHERE (is_default = true);--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_class_idx" ON "outreach_reply_threads" USING btree ("reply_class" text_ops,"first_inbound_at" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_reply_threads_email_uniq" ON "outreach_reply_threads" USING btree ("mailbox_id" uuid_ops,"gmail_thread_id" uuid_ops) WHERE ((channel = 'email'::text) AND (mailbox_id IS NOT NULL));--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_enrollment_idx" ON "outreach_reply_threads" USING btree ("enrollment_id" uuid_ops) WHERE (enrollment_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_first_inbound_idx" ON "outreach_reply_threads" USING btree ("first_inbound_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "outreach_reply_threads_linkedin_uniq" ON "outreach_reply_threads" USING btree ("unipile_account_id" text_ops,"gmail_thread_id" text_ops) WHERE ((channel = 'linkedin'::text) AND (unipile_account_id IS NOT NULL));--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_needs_class_idx" ON "outreach_reply_threads" USING btree ("last_inbound_at" timestamptz_ops) WHERE (reply_class IS NULL);--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_sequence_idx" ON "outreach_reply_threads" USING btree ("sequence_id" uuid_ops) WHERE (sequence_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "outreach_reply_threads_status_idx" ON "outreach_reply_threads" USING btree ("status" text_ops,"last_inbound_at" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_send_tasks_due_idx" ON "outreach_send_tasks" USING btree ("status" text_ops,"scheduled_for" text_ops);--> statement-breakpoint
CREATE INDEX "outreach_send_tasks_enrollment_idx" ON "outreach_send_tasks" USING btree ("enrollment_id" uuid_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "outreach_send_tasks_queue_idx" ON "outreach_send_tasks" USING btree ("channel" text_ops,"status" text_ops,"scheduled_for" text_ops) WHERE (status = 'ready'::text);--> statement-breakpoint
CREATE INDEX "outreach_send_tasks_sent_at_idx" ON "outreach_send_tasks" USING btree ("sent_at" timestamptz_ops) WHERE (status = 'sent'::text);--> statement-breakpoint
CREATE INDEX "social_yolo_posts_status_idx" ON "social_yolo_posts" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "social_yolo_posts_user_batch_idx" ON "social_yolo_posts" USING btree ("user_email" date_ops,"batch_date" date_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "social_yolo_posts_user_batch_position_idx" ON "social_yolo_posts" USING btree ("user_email" int4_ops,"batch_date" int4_ops,"position" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "research_rows_table_domain_uniq" ON "research_rows" USING btree (table_id text_ops,lower(domain) text_ops) WHERE (domain IS NOT NULL);--> statement-breakpoint
CREATE INDEX "research_rows_table_score_idx" ON "research_rows" USING btree ("table_id" numeric_ops,"icp_score" numeric_ops);--> statement-breakpoint
CREATE INDEX "research_rows_table_status_idx" ON "research_rows" USING btree ("table_id" text_ops,"status" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "user_voice_profiles_user_email_uidx" ON "user_voice_profiles" USING btree ("user_email" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "research_tables_slug_uniq" ON "research_tables" USING btree ("slug" text_ops) WHERE (slug IS NOT NULL);--> statement-breakpoint
CREATE INDEX "idx_scheduled_jobs_enabled" ON "scheduled_jobs" USING btree ("enabled" bool_ops) WHERE (enabled = true);--> statement-breakpoint
CREATE INDEX "product_signals_history_org_idx" ON "product_signals_history" USING btree ("org_id" text_ops,"computed_at" text_ops);--> statement-breakpoint
CREATE INDEX "x_reply_candidates_target_idx" ON "x_reply_candidates" USING btree ("target_account_id" timestamptz_ops,"post_created_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "x_reply_candidates_user_post_uidx" ON "x_reply_candidates" USING btree ("user_email" text_ops,"x_post_id" text_ops);--> statement-breakpoint
CREATE INDEX "x_reply_candidates_user_status_idx" ON "x_reply_candidates" USING btree ("user_email" text_ops,"status" text_ops,"post_created_at" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "research_evidence_row_criterion_uniq" ON "research_evidence" USING btree ("row_id" text_ops,"criterion_id" text_ops);--> statement-breakpoint
CREATE INDEX "research_evidence_row_idx" ON "research_evidence" USING btree ("row_id" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "user_notifications_dedupe_uniq" ON "user_notifications" USING btree ("user_email" text_ops,"dedupe_key" text_ops);--> statement-breakpoint
CREATE INDEX "user_notifications_user_idx" ON "user_notifications" USING btree ("user_email" timestamptz_ops,"read_at" text_ops,"created_at" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "research_excluded_table_company_uniq" ON "research_excluded_companies" USING btree ("table_id" text_ops,"company_key" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "research_excluded_table_domain_uniq" ON "research_excluded_companies" USING btree (table_id text_ops,lower(domain) text_ops) WHERE (domain IS NOT NULL);--> statement-breakpoint
CREATE INDEX "company_enrichment_fetched_idx" ON "company_enrichment" USING btree ("fetched_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "goal_links_goal_idx" ON "goal_links" USING btree ("goal_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "goal_links_work_item_idx" ON "goal_links" USING btree ("work_item_id" uuid_ops);--> statement-breakpoint
CREATE POLICY "crm_status_sla_update" ON "crm_status_sla" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "crm_status_sla_select" ON "crm_status_sla" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_status_sla_insert" ON "crm_status_sla" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_status_sla_delete" ON "crm_status_sla" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_field_defs_update" ON "crm_field_defs" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "crm_field_defs_select" ON "crm_field_defs" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_field_defs_insert" ON "crm_field_defs" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_field_defs_delete" ON "crm_field_defs" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role manages conversations" ON "conversations" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "crm_companies_update" ON "crm_companies" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "crm_companies_select" ON "crm_companies" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_companies_insert" ON "crm_companies" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_companies_delete" ON "crm_companies" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_comments_update" ON "crm_comments" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "crm_comments_select" ON "crm_comments" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_comments_insert" ON "crm_comments" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_comments_delete" ON "crm_comments" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role can manage goals" ON "goals" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can write goals" ON "goals" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Authenticated users can read goals" ON "goals" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role can manage goal_recurrences" ON "goal_recurrences" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can write goal_recurrences" ON "goal_recurrences" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Authenticated users can read goal_recurrences" ON "goal_recurrences" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role manages job_runs" ON "job_runs" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "linkedin_commenter_triggers_select" ON "linkedin_commenter_triggers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Service role can manage snapshots" ON "llm_mentions_snapshots" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can read snapshots" ON "llm_mentions_snapshots" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role can manage prospects" ON "outreach_prospects" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can write prospects" ON "outreach_prospects" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Authenticated users can read prospects" ON "outreach_prospects" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_auto_enroll_rules_update" ON "outreach_auto_enroll_rules" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_auto_enroll_rules_select" ON "outreach_auto_enroll_rules" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_auto_enroll_rules_insert" ON "outreach_auto_enroll_rules" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_auto_enroll_rules_delete" ON "outreach_auto_enroll_rules" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_enrollments_update" ON "outreach_enrollments" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_enrollments_select" ON "outreach_enrollments" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_enrollments_insert" ON "outreach_enrollments" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_enrollments_delete" ON "outreach_enrollments" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_messages_update" ON "outreach_reply_messages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_reply_messages_select" ON "outreach_reply_messages" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_messages_insert" ON "outreach_reply_messages" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_messages_delete" ON "outreach_reply_messages" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequence_snapshots_select" ON "outreach_sequence_snapshots" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_sequence_snapshots_insert" ON "outreach_sequence_snapshots" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_people_snapshots_select" ON "research_people_snapshots" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_people_snapshots_insert" ON "research_people_snapshots" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_runs_update" ON "research_runs" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_runs_select" ON "research_runs" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_runs_insert" ON "research_runs" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_runs_delete" ON "research_runs" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_table_snapshots_select" ON "research_table_snapshots" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_table_snapshots_insert" ON "research_table_snapshots" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequences_update" ON "outreach_sequences" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_sequences_select" ON "outreach_sequences" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequences_insert" ON "outreach_sequences" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequences_delete" ON "outreach_sequences" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_people_update" ON "research_people" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_people_select" ON "research_people" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_people_insert" ON "research_people" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_people_delete" ON "research_people" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "product_signals_latest_select" ON "product_signals_latest" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Service role can manage mentions" ON "social_mentions" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can read mentions" ON "social_mentions" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_activities_update" ON "crm_activities" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "crm_activities_select" ON "crm_activities" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_activities_insert" ON "crm_activities" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_activities_delete" ON "crm_activities" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_contacts_update" ON "crm_contacts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "crm_contacts_select" ON "crm_contacts" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_contacts_insert" ON "crm_contacts" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "crm_contacts_delete" ON "crm_contacts" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "growth_work_items_update" ON "growth_work_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "growth_work_items_select" ON "growth_work_items" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "growth_work_items_insert" ON "growth_work_items" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "growth_work_items_delete" ON "growth_work_items" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "enrichment_cache_update" ON "enrichment_cache" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "enrichment_cache_select" ON "enrichment_cache" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "enrichment_cache_insert" ON "enrichment_cache" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "enrichment_cache_delete" ON "enrichment_cache" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "linkedin_commenters_select" ON "linkedin_commenters" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "kanban_columns_update" ON "kanban_columns" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "kanban_columns_select" ON "kanban_columns" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "kanban_columns_insert" ON "kanban_columns" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "kanban_columns_delete" ON "kanban_columns" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_mailboxes_update" ON "outreach_mailboxes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_mailboxes_select" ON "outreach_mailboxes" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_mailboxes_insert" ON "outreach_mailboxes" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_mailboxes_delete" ON "outreach_mailboxes" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_threads_update" ON "outreach_reply_threads" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_reply_threads_select" ON "outreach_reply_threads" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_threads_insert" ON "outreach_reply_threads" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_reply_threads_delete" ON "outreach_reply_threads" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_send_tasks_update" ON "outreach_send_tasks" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_send_tasks_select" ON "outreach_send_tasks" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_send_tasks_insert" ON "outreach_send_tasks" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_send_tasks_delete" ON "outreach_send_tasks" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequence_steps_update" ON "outreach_sequence_steps" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "outreach_sequence_steps_select" ON "outreach_sequence_steps" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequence_steps_insert" ON "outreach_sequence_steps" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "outreach_sequence_steps_delete" ON "outreach_sequence_steps" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_rows_update" ON "research_rows" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_rows_select" ON "research_rows" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_rows_insert" ON "research_rows" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_rows_delete" ON "research_rows" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_tables_update" ON "research_tables" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_tables_select" ON "research_tables" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_tables_insert" ON "research_tables" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_tables_delete" ON "research_tables" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Service role manages scheduled_jobs" ON "scheduled_jobs" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "product_signals_history_select" ON "product_signals_history" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_evidence_update" ON "research_evidence" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_evidence_select" ON "research_evidence" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_evidence_insert" ON "research_evidence" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_evidence_delete" ON "research_evidence" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_excluded_companies_update" ON "research_excluded_companies" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "research_excluded_companies_select" ON "research_excluded_companies" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_excluded_companies_insert" ON "research_excluded_companies" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "research_excluded_companies_delete" ON "research_excluded_companies" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "company_enrichment_select" ON "company_enrichment" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Service role can manage goal_links" ON "goal_links" AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can write goal_links" ON "goal_links" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Authenticated users can read goal_links" ON "goal_links" AS PERMISSIVE FOR SELECT TO "authenticated";
*/