/**
 * Medium, through its own "Import a story" page.
 *
 * Medium stopped issuing API integration tokens in 2023, so there is no
 * publishing API to call. What it still offers is an import form: paste the
 * URL of a page, and Medium copies it into a new story with the canonical set
 * back to that page. That is exactly the shape of a crosspost — the original
 * on a site we own keeps the credit — so a Medium channel never types content
 * into Medium. It imports the page the persona already published.
 *
 * Two facts about Medium's distribution shape everything here:
 *  - AI-written text without a disclosure in its first two paragraphs is shown
 *    to the author's followers only. Importing it is a wasted session, so the
 *    source page is checked for a disclosure before the browser is opened.
 *  - The login is a cookie jar in a persistent Browserbase context. The person
 *    logs in once through the live view; the tool reuses the context and never
 *    holds a password.
 *
 * Fragile by nature — it depends on Medium's DOM — so the selectors are role-
 * and text-based, and every step reports which one failed.
 */
import { withBrowserPage } from "@/lib/influencer/browser";
import { isOwnedCanonical } from "@/lib/influencer/url-guard";
import type { PersonaActivity, PersonaChannel } from "@/lib/influencer/types";

export const MEDIUM_IMPORT_URL = "https://medium.com/p/import";
export const MEDIUM_SIGNIN_URL = "https://medium.com/m/signin";

/** Where the Medium channel keeps its login: the id of a persistent context. */
export const MEDIUM_CONTEXT_KEY = "browserbase_context_id";

/** What credentials_ref says once a Medium channel is connected. Not an env
 *  var name, on purpose: nothing resolves it as one. */
export const MEDIUM_CREDENTIAL_MARKER = "browserbase:medium";

export function mediumContextId(channel: Pick<PersonaChannel, "channel_config">): string | null {
  const raw = channel.channel_config[MEDIUM_CONTEXT_KEY];
  return typeof raw === "string" && raw.trim() ? raw.trim() : null;
}

/**
 * The page a Medium activity imports. Only a crosspost carries one, and it has
 * to be a canonical on a site we own — anything else would either import a
 * page that isn't ours or publish content Medium has no source for.
 */
export function mediumSourceUrl(activity: Pick<PersonaActivity, "kind" | "content_meta">): {
  url: string | null;
  reason: string | null;
} {
  if (activity.kind !== "crosspost") {
    return {
      url: null,
      reason:
        "Medium publishes by importing a page we already published. Queue a crosspost (kind 'crosspost') with canonical_url set to that page.",
    };
  }
  const raw = activity.content_meta?.canonical_url;
  const url = typeof raw === "string" ? raw.trim() : "";
  if (!url) {
    return { url: null, reason: "Medium crosspost has no canonical_url to import." };
  }
  if (!isOwnedCanonical(url)) {
    return { url: null, reason: `canonical_url ${url} is not on a site we own; Medium imports only our own pages.` };
  }
  return { url, reason: null };
}

/**
 * Medium's rule: a disclosure sentence in the first two paragraphs, or the
 * story reaches followers only. Two paragraphs of a web page is roughly the
 * first 1,500 characters of its readable text. The patterns are the shapes
 * Medium's own help page uses ("written with the assistance of an AI writing
 * program") plus the fleet's own line ("an AI ... operated by").
 */
export function hasAiDisclosure(text: string, personaDisclosure?: string | null): boolean {
  const head = text.replace(/\s+/g, " ").trim().slice(0, 1_500).toLowerCase();
  if (!head) return false;
  const own = personaDisclosure?.replace(/\s+/g, " ").trim().toLowerCase();
  if (own && own.length >= 8 && head.includes(own)) return true;
  const AI = "(ai|artificial intelligence|language model|llm|ai writing program)";
  // "…an AI wrote/assisted/generated…" and "…written/generated by/with an AI…".
  const aiThenVerb = new RegExp(`\\b${AI}\\b[^.]{0,80}\\b(assist|generat|wrote|writ|produc|operat|draft)`);
  const verbThenAi = new RegExp(
    `\\b(assist\\w*|generat\\w*|written|produced|drafted|created)\\b[^.]{0,40}\\b(by|with)\\b[^.]{0,30}\\b${AI}\\b`,
  );
  return aiThenVerb.test(head) || verbThenAi.test(head);
}

/** Readable text of an HTML page, no tags, scripts or styles. Good enough for a
 *  disclosure check; never for anything that reads meaning into markup. */
const ENTITIES: Record<string, string> = {
  nbsp: " ",
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  "#39": "'",
};

export function htmlToText(html: string): string {
  return (
    html
      // The end tag may carry whitespace (</script >); the body may hold
      // anything, including a "<" that is not a tag.
      .replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi, " ")
      .replace(/<style\b[^>]*>[\s\S]*?<\/style\s*>/gi, " ")
      .replace(/<\/(p|div|h[1-6]|li|br|section|article)\s*>/gi, "\n")
      .replace(/<[^>]+>/g, " ")
      // One pass over entities, so "&amp;lt;" decodes to "&lt;" and stops there.
      .replace(/&(nbsp|amp|lt|gt|quot|#39);/g, (_, name: string) => ENTITIES[name] ?? "")
      .replace(/[ \t]+/g, " ")
      .replace(/ ?\n ?/g, "\n")
      .replace(/\n\s*\n+/g, "\n")
      .trim()
  );
}

/** Whether the channel asks for the disclosure check. On unless it says off —
 *  turning it off is a choice someone makes knowing the story stays network-only. */
export function requiresDisclosure(channel: Pick<PersonaChannel, "channel_config">): boolean {
  return channel.channel_config.require_disclosure !== false;
}

/** Medium's editor for a story lives at /p/<hex id>/edit. Landing there is what
 *  says the import worked. */
export function isMediumEditorUrl(url: string): boolean {
  try {
    const u = new URL(url);
    return /(^|\.)medium\.com$/i.test(u.hostname) && /^\/p\/[a-f0-9]+\/edit\/?$/i.test(u.pathname);
  } catch {
    return false;
  }
}

/** Anything under /m/signin (or the account-less landing) means the context's
 *  login has expired and the person has to sign in again. */
export function isMediumSignInUrl(url: string): boolean {
  try {
    const u = new URL(url);
    return /(^|\.)medium\.com$/i.test(u.hostname) && /^\/m\/(signin|login)/i.test(u.pathname);
  } catch {
    return false;
  }
}

/** A published story's URL — never the editor, never the import page. */
export function isMediumStoryUrl(url: string): boolean {
  try {
    const u = new URL(url);
    if (!/(^|\.)medium\.com$/i.test(u.hostname)) return false;
    if (isMediumEditorUrl(url) || isMediumSignInUrl(url)) return false;
    if (/^\/p\/import/i.test(u.pathname) || /^\/new-story/i.test(u.pathname)) return false;
    // Stories end in a 12-hex id: /@handle/some-slug-0123456789ab or /p/<id>.
    return /[a-f0-9]{12}\/?$/i.test(u.pathname);
  } catch {
    return false;
  }
}

export type MediumImportResult = {
  imported: boolean;
  published: boolean;
  url: string | null;
  /** Where it stopped, for the failure message. */
  stage: "open" | "signin" | "form" | "import" | "publish" | "done";
};

/**
 * Drive the import: open the form, paste the URL, import, publish. `dryRun`
 * stops at the editor with the story imported but not published — the way to
 * check the login and the selectors without putting anything on Medium.
 */
export async function importStoryOnMedium(
  sourceUrl: string,
  opts: { contextId: string; dryRun?: boolean; proxies?: boolean; timeoutMs?: number },
): Promise<MediumImportResult> {
  if (!isOwnedCanonical(sourceUrl)) {
    throw new Error("Medium imports only pages on a site we own.");
  }
  const timeout = opts.timeoutMs ?? 45_000;

  return withBrowserPage(
    { contextId: opts.contextId, proxies: opts.proxies, timeoutSeconds: 4 * 60 },
    async (page) => {
      await page.goto(MEDIUM_IMPORT_URL, { waitUntil: "domcontentloaded", timeout });
      await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
      if (isMediumSignInUrl(page.url())) {
        return { imported: false, published: false, url: null, stage: "signin" };
      }

      // The import form: one URL field and one Import button. Role and
      // placeholder first; a bare input as the last resort.
      const field = page
        .locator('input[type="url"], input[placeholder*="link" i], input[placeholder*="url" i], input[type="text"]')
        .first();
      const fieldVisible = await field
        .waitFor({ state: "visible", timeout: 15_000 })
        .then(() => true)
        .catch(() => false);
      if (!fieldVisible) {
        if (isMediumSignInUrl(page.url())) {
          return { imported: false, published: false, url: null, stage: "signin" };
        }
        return { imported: false, published: false, url: null, stage: "form" };
      }
      await field.click();
      await field.fill(sourceUrl);
      const importButton = page.getByRole("button", { name: /^import$/i }).first();
      await importButton.waitFor({ state: "visible", timeout: 10_000 });
      await importButton.click();

      // Medium fetches the page server-side and opens the editor on it.
      const inEditor = await page
        .waitForURL((u) => isMediumEditorUrl(u.toString()), { timeout })
        .then(() => true)
        .catch(() => false);
      if (!inEditor) {
        return { imported: false, published: false, url: page.url(), stage: "import" };
      }
      await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
      if (opts.dryRun) {
        return { imported: true, published: false, url: page.url(), stage: "done" };
      }

      // Publish: the editor's Publish button opens a pre-publish panel whose
      // confirm is "Publish now". Either can be missing when the DOM moves;
      // failing here leaves an imported draft in the account, nothing public.
      const publish = page.getByRole("button", { name: /^publish$/i }).first();
      await publish.waitFor({ state: "visible", timeout: 15_000 });
      await publish.click();
      const publishNow = page.getByRole("button", { name: /publish now/i }).first();
      await publishNow.waitFor({ state: "visible", timeout: 15_000 });
      await publishNow.click();

      const story = await page
        .waitForURL((u) => isMediumStoryUrl(u.toString()), { timeout })
        .then(() => true)
        .catch(() => false);
      if (!story) {
        return { imported: true, published: false, url: page.url(), stage: "publish" };
      }
      await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
      return { imported: true, published: true, url: page.url(), stage: "done" };
    },
  );
}

/**
 * Is this context still logged in to Medium? Opening the import page answers
 * it: a signed-out session is bounced to sign-in. Costs one short session;
 * the connect form runs it so "connected" means something.
 */
export async function checkMediumSession(
  contextId: string,
  opts?: { proxies?: boolean },
): Promise<{ loggedIn: boolean; landedOn: string }> {
  return withBrowserPage({ contextId, proxies: opts?.proxies, timeoutSeconds: 90 }, async (page) => {
    await page.goto(MEDIUM_IMPORT_URL, { waitUntil: "domcontentloaded", timeout: 30_000 });
    await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
    const landedOn = page.url();
    if (isMediumSignInUrl(landedOn)) return { loggedIn: false, landedOn };
    const hasForm = await page
      .locator('input[type="url"], input[placeholder*="link" i], input[placeholder*="url" i], input[type="text"]')
      .first()
      .waitFor({ state: "visible", timeout: 10_000 })
      .then(() => true)
      .catch(() => false);
    return { loggedIn: hasForm, landedOn };
  });
}

/**
 * Fetch the source page and decide whether Medium would distribute it. Pure
 * check over the page text; the fetch is of our own page, so no SSRF guard
 * beyond the owned-domain one that already gated the URL.
 */
export async function sourceDiscloses(
  sourceUrl: string,
  personaDisclosure: string | null | undefined,
): Promise<{ ok: boolean; reason: string | null }> {
  const res = await fetch(sourceUrl, { cache: "no-store", redirect: "follow" });
  if (!res.ok) {
    return { ok: false, reason: `Source page returned HTTP ${res.status}; nothing to import.` };
  }
  const html = await res.text();
  const text = htmlToText(html);
  if (hasAiDisclosure(text, personaDisclosure)) return { ok: true, reason: null };
  return {
    ok: false,
    reason:
      "The source page has no AI disclosure in its first two paragraphs. Medium shows undisclosed AI writing to followers only, so this import would reach nobody. Revise the original (read_post + replaces_slug) to open with a line such as \"This story was written with the assistance of an AI writing program.\", then crosspost again. Set channel_config.require_disclosure=false to import anyway.",
  };
}
