/**
 * Medium is published by importing a page of ours, never by typing into it.
 * These pin the pure decisions around that: which activity may be imported,
 * whether the page would even be distributed, and how the browser tells the
 * editor, the sign-in bounce and a published story apart by URL.
 */
import { describe, expect, it } from "vitest";

import {
  hasAiDisclosure,
  htmlToText,
  isMediumEditorUrl,
  isMediumSignInUrl,
  isMediumStoryUrl,
  mediumContextId,
  mediumSourceUrl,
  requiresDisclosure,
} from "../../lib/influencer/medium";

describe("mediumSourceUrl", () => {
  it("imports the canonical of a crosspost on a site we own", () => {
    const r = mediumSourceUrl({
      kind: "crosspost",
      content_meta: { canonical_url: "https://aicodereview.io/blog/some-post" },
    });
    expect(r).toEqual({ url: "https://aicodereview.io/blog/some-post", reason: null });
  });

  it("refuses anything that is not a crosspost — nothing is typed into Medium", () => {
    const r = mediumSourceUrl({ kind: "article", content_meta: { canonical_url: "https://aicodereview.io/x" } });
    expect(r.url).toBeNull();
    expect(r.reason).toMatch(/crosspost/);
  });

  it("refuses a crosspost with no canonical, and one pointing off our sites", () => {
    expect(mediumSourceUrl({ kind: "crosspost", content_meta: {} }).url).toBeNull();
    const off = mediumSourceUrl({
      kind: "crosspost",
      content_meta: { canonical_url: "https://coderabbit.ai/blog/theirs" },
    });
    expect(off.url).toBeNull();
    expect(off.reason).toMatch(/not on a site we own/);
  });
});

describe("hasAiDisclosure", () => {
  it("accepts Medium's own example sentence", () => {
    expect(
      hasAiDisclosure("Intro paragraph. This story was written with the assistance of an AI writing program. More."),
    ).toBe(true);
  });

  it("accepts the fleet's disclosure line when the persona has one", () => {
    expect(hasAiDisclosure("Hi. I'm an AI agent operated by Kodus. Today…", "I'm an AI agent operated by Kodus.")).toBe(
      true,
    );
  });

  it("accepts 'generated by an AI' and 'an LLM drafted' phrasings", () => {
    expect(hasAiDisclosure("Note: this post was generated by an AI and edited by a human.")).toBe(true);
    expect(hasAiDisclosure("An LLM drafted this piece; I checked the numbers.")).toBe(true);
  });

  it("ignores a disclosure buried past the first two paragraphs", () => {
    const filler = "word ".repeat(400);
    expect(hasAiDisclosure(`${filler} This story was written with the assistance of an AI writing program.`)).toBe(
      false,
    );
  });

  it("does not mistake a post ABOUT AI for a disclosure", () => {
    expect(hasAiDisclosure("AI code review tools compared: which one catches real bugs?")).toBe(false);
    expect(hasAiDisclosure("")).toBe(false);
  });
});

describe("htmlToText", () => {
  it("drops scripts, styles and tags and keeps paragraph breaks", () => {
    const html =
      "<html><head><style>p{}</style><script>x()</script></head><body><h1>T</h1><p>One &amp; two</p><p>Three</p></body></html>";
    expect(htmlToText(html)).toBe("T\nOne & two\nThree");
  });

  it("matches a script end tag with whitespace and never double-decodes an entity", () => {
    expect(htmlToText("<p>a</p><script>x()</script ><p>b</p>")).toBe("a\nb");
    expect(htmlToText("<p>a</p><script>x()</script\t\n bar><p>b</p>")).toBe("a\nb");
    expect(htmlToText("<p>&amp;lt;</p>")).toBe("&lt;");
  });
});

describe("Medium URLs", () => {
  it("knows the editor", () => {
    expect(isMediumEditorUrl("https://medium.com/p/0123abcdef/edit")).toBe(true);
    expect(isMediumEditorUrl("https://medium.com/p/import")).toBe(false);
    expect(isMediumEditorUrl("https://example.com/p/0123abcdef/edit")).toBe(false);
  });

  it("knows the sign-in bounce", () => {
    expect(isMediumSignInUrl("https://medium.com/m/signin?operation=login")).toBe(true);
    expect(isMediumSignInUrl("https://medium.com/p/import")).toBe(false);
  });

  it("knows a published story from the editor and the import page", () => {
    expect(isMediumStoryUrl("https://medium.com/@persona/my-story-0123456789ab")).toBe(true);
    expect(isMediumStoryUrl("https://medium.com/p/0123456789ab")).toBe(true);
    expect(isMediumStoryUrl("https://medium.com/p/0123456789ab/edit")).toBe(false);
    expect(isMediumStoryUrl("https://medium.com/p/import")).toBe(false);
    expect(isMediumStoryUrl("https://medium.com/new-story")).toBe(false);
  });
});

describe("channel config", () => {
  it("reads the context id and the disclosure switch", () => {
    expect(mediumContextId({ channel_config: { browserbase_context_id: " ctx1 " } })).toBe("ctx1");
    expect(mediumContextId({ channel_config: {} })).toBeNull();
    expect(requiresDisclosure({ channel_config: {} })).toBe(true);
    expect(requiresDisclosure({ channel_config: { require_disclosure: false } })).toBe(false);
  });
});
