-- The index is created concurrently by the db-migrate workflow after
-- `supabase db push` completes. CREATE INDEX CONCURRENTLY cannot run inside
-- the transaction used by Supabase migrations, so this migration is the
-- versioned marker while the operational DDL lives in supabase/operations/.
